version: "3"

services:
    home:
        image: christiannxtlvl/php-server:7.4
        container_name: home
        ports:
            - '84:80'
        environment:
            PICO_URL_REWRITING: 1
        volumes: 
            - ./:/var/www/html