version: "3"

services:
    home:
        image: christiangroeber/php-server:8.1.2
        container_name: home
        ports:
            - '84:80'
        environment:
            PICO_URL_REWRITING: 1
        volumes: 
            - ./:/var/www/html