version: "3"

services:
    pico:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '84:80'
        environment:
            PICO_URL_REWRITING: 1
        volumes: 
            - ./public:/var/www/html
            - ./:/app